DROP DATABASE IF EXISTS DEV;
DROP DATABASE IF EXISTS TEST;
CREATE DATABASE DEV;
CREATE DATABASE TEST;

USE DEV;
CREATE TABLE user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  firstName VARCHAR(256),
  lastName VARCHAR(256),
  isActive BOOLEAN DEFAULT true);
